###
GET http://localhost:11434

###
GET http://localhost:11434/api/version

### Get all tags
GET http://localhost:11434/api/tags

### ollama generate
POST http://localhost:11434/api/generate
Content-Type: application/json

{
    "model": "gemma3:latest",
    "prompt": "당신은 누구입니까?",
    "stream": false
}

### ollama pull
POST http://localhost:22244/api/pull
Content-Type: application/json

{"name": "exaone3.5:2.4b"}
